// <auto-generated />
using System;
using Employee.Sample.Services.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employee.Sample.Migrations.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    partial class EmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Employee.Sample.Data.DataModels.EmployeeData", b =>
                {
                    b.Property<string>("_email")
                        .HasMaxLength(320)
                        .HasColumnType("VARCHAR(320)");

                    b.Property<DateTime>("_joined")
                        .HasColumnType("datetime2");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("_tell")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("_email");

                    b.HasIndex("_name");

                    b.ToTable("TblEmployee", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
